### ISSUE TITLE
Display names for attributes?

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ontology-management-base#113]
Do shacles have the option to define a "display name" as otherwise we have to parse this name` sh:name "measurementSystem"@en ;` and change it to display it on a website e.g.

**Comment by MircoNierenz** [comment]
the sh::name is the display name. i will have a look at the asset shacls in this regard.

**Comment by MircoNierenz** [comment]
change "measurementSystem" to more readable "measurement system"
