### ISSUE TITLE
Harmonization of scenario metadata to other data categories

### ISSUE THREAD

**Issue by heuerfin** [GAIA-X4PLC-AAD/ontology-management-base#120]
The other data categories are strucutred in format, content, quantity, quality, and dataSource. This should also apply for the scenario category. According to alignment meeting of data providers.

**Comment by heuerfin** [comment]
Applied changes. Review pending

**Comment by jtdemer** [comment]
Looks good from my side. 
@heuerfin do you want to create an pull request?

**Comment by heuerfin** [comment]
Thanks for the hint, created the PR.
