### ISSUE TITLE
Issue on Surface Model Ontology

### ISSUE THREAD

**Issue by 3Dbastian** [GAIA-X4PLC-AAD/ontology-management-base#20]
@3Dbastian @MircoNierenz @JustinDxx @jtdemer 
refers to Pull Request
#14 
The field origin in the SHACL is defined with a single float value, but two or threes coordinates are needed.

Ideas on the solutions: 
(i) is it better within the xsd datatypes to have an string with a defined format to represent the coordinates
(ii) shall we define minCount ==2 and maxCount ==3
(iii) is there a available data type to define a numeric tuple within xsd

This questions is similar to the problem in this issue:
https://github.com/GAIA-X4PLC-AAD/map-and-scenario-data/issues/6#issue-2175811114

**Comment by MircoNierenz** [comment]
fixed
