### ISSUE TITLE
LICENSE MISSING

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ontology-management-base#22]
I actually lean towarld MPL-2.0

Update: Due to the input I am ok with EPL 2.0

**Comment by jdsika** [comment]
@lenasauermann please provide all documents this repository is relying as links to the original source including the licenses used in the references. This is a critical information for us and we need this asap

**Comment by lenasauermann** [comment]
FC Repo with Base Gaia-X Shapes https://gitlab.eclipse.org/eclipse/xfsc/cat/fc-service : Apache License 2.0
Shapes von Gaia-X WG https://gitlab.com/gaia-x/technical-committee/service-characteristics : Eclipse Public License 2.0
Gaia-X Trustframework 22.10 https://docs.gaia-x.eu/policy-rules-committee/trust-framework/latest/editorial_information/ : Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License --> eventuell nur für das Dokument relevant

**Comment by lenasauermann** [comment]
Policy and Rules Confirmity Document: https://docs.gaia-x.eu/policy-rules-committee/policy-rules-conformity-document/latest/ komische License

**Comment by robertschubert** [comment]
> https://github.com/GAIA-X4PLC-AAD/ontology-management-base/issues/22#issuecomment-2056703976
The CREATIVE COMMONS license described here relates only to the specific document, not to the artifacts described. The sentence "Third party material or references are cited in this document." (not sure if it is new) should underline this.

**Comment by robertschubert** [comment]
My proposal for license in this repository ist EPL-2.0.
Reasons:

- this license is used also for the repositories not running under eclipse, e. g. https://gitlab.com/gaia-x/technical-committee/service-characteristics. So we achieve some kind of homogen set of licenses.
- we remain a weak copyleft here.
- Compatibility With GPL is not relevant, at least for now.

But: I am also fine with MPL-2.0 but we have the risk of patent issues (which is not much likely). MIT also good for me but we lose the weak copyleft und must hope that changes / proposals will be reflected by PR by the community.

**Comment by jdsika** [comment]
> My proposal for license in this repository ist EPL-2.0. Reasons:
> 
>     * this license is used also for the repositories not running under eclipse, e. g. https://gitlab.com/gaia-x/technical-committee/service-characteristics. So we achieve some kind of homogen set of licenses.
> 
>     * we remain a weak copyleft here.
> 
>     * Compatibility With GPL is not relevant, at least for now.
> 
> 
> But: I am also fine with MPL-2.0 but we have the risk of patent issues (which is not much likely). MIT also good for me but we lose the weak copyleft und must hope that changes / proposals will be reflected by PR by the community.

ok, we have all 3 options on the table. In fact the active contributors are the ones deciding this eventually and the ones who want to contribute in the future must be ok with it as well. Being in line with other licenses at GaiaX is a good argument.

I AM OK WITH EPL 2.0 and I have changed my PR accordingly

**Comment by jdsika** [comment]
We can also demonstrate nicely that you do not have to use the same license subsequently by e.g. using MPL 2.0 [here](https://github.com/GAIA-X4PLC-AAD/hd-map-asset-example/issues/1) as this will likely find its way into OpenMSL

**Comment by jdsika** [comment]
@robertschubert please approve and merge my license PR

**Comment by robertschubert** [comment]
@jdsika I added one review remark. After this is clear I will merge it.
