### ISSUE TITLE
404: not found

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ontology-management-base#25]
@prefix gax-trust-framework: <http://w3id.org/gaia-x/gax-trust-framework#>

**Comment by robertschubert** [comment]
Will be replaced by
https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#
for now. Mirco is informed and will apply this change.
This URL will change in the next release called "Loire"

**Comment by robertschubert** [comment]
Fell free to close this issue.
