### ISSUE TITLE
 TODOS discussion 06.05.2024

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ontology-management-base#29]
# Participants
@robertschubert 
@jtdemer 
@jdsika 

# Decisions

1) Every ontology is created in its own folder
   Codeowners
   Rename: VARAIBLES -> prefix_properties.md OR PROPERTIES.md
   files and folders without capitals
   prefix is always the same as the folder name
   prefix names use "-" as separators
   Classes PascalCase
   Properties camlCase
2) Rename examples folder to example
   Carlo: merge examples. Question of taste
3) Add test vector as example .json file into each ontology folder
   not extra folder, just same level
   everyone adding an ontology must add an example
4) Add CI workflows
   test if ontology/shacl parses successfully
   test if example .json complies with shacl property definitions (schema)
5) Add gaiax ontologies as sub repository and link resources in readme
   GaiaX definitions are provided as json and not as a repo
   we add an extra folder to the repo named e.g. "gaiax" with a readme and original json plus pthon converter to .ttl
6) Can we discuss some structural elements used in the old demo as Carlo thinks it is useful
   [token meta data](https://github.com/AlgedonicLoop/SMSIWTDemo/blob/develop/demo/contract/OSMPDummySensor.json)

**Comment by robertschubert** [comment]
#5 is done, see [PR](https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/30)

**Comment by robertschubert** [comment]
[] Every ontology is created in its own folder
   [] Codeowners
   [] Rename: VARAIBLES -> prefix_properties.md OR PROPERTIES.md
   [] files and folders without capitals
   [] prefix is always the same as the folder name
   [] prefix names use "-" as separators
   [] Classes PascalCase
   [] Properties camlCase
[] Rename examples folder to example
   [] Carlo: merge examples. Question of taste
[] Add test vector as example .json file into each ontology folder
   [] not extra folder, just same level
   [] everyone adding an ontology must add an example
[] Add CI workflows
   [] test if ontology/shacl parses successfully
   [] test if example .json complies with shacl property definitions (schema)
[x] Add gaiax ontologies as sub repository and link resources in readme
   [x] GaiaX definitions are provided as json and not as a repo
   [x] we add an extra folder to the repo named e.g. "gaiax" with a readme and original json plus pthon converter to .ttl
[] Can we discuss some structural elements used in the old demo as Carlo thinks it is useful
   [] [token meta data](https://github.com/AlgedonicLoop/SMSIWTDemo/blob/develop/demo/contract/OSMPDummySensor.json)

**Comment by robertschubert** [comment]
regarding 
"test if example .json complies with shacl property definitions (schema)"

This task is simple for shapes that do not reference "external" shapes.

Example:
```
prefix:SomeShape a sh:NodeShape ;
    sh:property [ sh:minCount 1 ;
            sh:node gx:PostalAddressShape ;
            sh:path general:myAddress;
            sh:order 5 ] ;
    sh:targetClass general:General .
```
With this syntax you would be able to reference an "external" `gx:PostalAddressShape`. The validation in the Federated Catalogue is no problem as long the `gx:PostalAddressShape` was uploaded before. **All** shapes are loaded for validation in the Federated Catalogue upfront.

In the context of this repository we will not have access to gx:PostalAddressShape so no validation against this shape is possible.

**Comment by jdsika** [comment]
Can the shapes also be uploaded somewhere more independend from EDC? Reference to a URL? I don't want to use custom software to access the shapes. Just a trusted source.

**Comment by robertschubert** [comment]
Task "-> test if ontology/shacl parses successfully":
solved with PR https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/58

**Comment by robertschubert** [comment]
> Can the shapes also be uploaded somewhere more independend from EDC? Reference to a URL? I don't want to use custom software to access the shapes. Just a trusted source.

@jdsika not sure if I understand the question. Which subtask are you referring to? Or where do we have a link to EDC in this issue / repository?

**Comment by jdsika** [comment]
I am sorry, I was reading this comment and may have misunderstood it? It was regarding "where" are the ontologies uploaded to in order to have a source for the validation.

> With this syntax you would be able to reference an "external" gx:PostalAddressShape. The validation in the Federated Catalogue is no problem as long the gx:PostalAddressShape was uploaded before. All shapes are loaded for validation in the Federated Catalogue upfront.

**Comment by robertschubert** [comment]
> I am sorry, I was reading this comment and may have misunderstood it? It was regarding "where" are the ontologies uploaded to in order to have a source for the validation.
> 
> > With this syntax you would be able to reference an "external" gx:PostalAddressShape. The validation in the Federated Catalogue is no problem as long the gx:PostalAddressShape was uploaded before. All shapes are loaded for validation in the Federated Catalogue upfront.

The source for validation is the federated catalogue. Ontologies and shapes must be uploaded so the catalogue knows what an HdMap is (as an example). The validation against the shacl shape is then done in the federated catalogue when someone uploads a self description containing an HdMap.

Since we now have a working (because fixed) gx ontology in our repo I will also have access to the PostalAddressShape in the context of this repo.
So it should work out to load all existent SHACLs and validate one json-ld against all loaded shapes. I will have a look.

**Comment by robertschubert** [comment]
Task "-> test if example .json complies with shacl property definitions (schema)":
solved with PR https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/58

**Comment by robertschubert** [comment]
@jdsika 
my proposal is that I create a new Issue for
**Rename: VARAIBLES -> prefix_properties.md OR PROPERTIES.md**
See https://github.com/GAIA-X4PLC-AAD/ontology-management-base/issues/71

After the open branches are merged I will make the change.

Is there anything else that has to be done in this Issue or can we close it?
