### ISSUE TITLE
Incomplete examples like skos:example "nan" 

### ISSUE THREAD

**Issue by robertschubert** [GAIA-X4PLC-AAD/ontology-management-base#36]
At least in ontology environment-model there are a bunch of `skos:example` with the value `nan`.

TODO:
either place a reasonable example instead of `nan` or remove the example at all. 

Arised from PR: https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/31

**Comment by rcrswld** [comment]
is fixed, s. https://github.com/GAIA-X4PLC-AAD/ontology-management-base/blob/main/environment-model/environment-model_shacl.ttl
