### ISSUE TITLE
Refactor shacl shapes to reduce duplication

### ISSUE THREAD

**Issue by robertschubert** [GAIA-X4PLC-AAD/ontology-management-base#37]
As discussed with @jtdemer and @rcrswld we should refactor the shacl shapes to reduce duplication of shapes.

As an example there is a `BoundingBoxShape` duplicated in several other ontologies. 

As I understood there will be a new GeoReferenceShape (name might sligtly change) where those geo informations will be encapsulated. After that this new shape can be encapsulated into the another ones with something like this:

```
     [ sh:minCount 1 ;
            sh:node geo-reference:GeoReferenceShape ;
            sh:path environment-model:geoInformation;
            sh:order 1 ] ;
```

**Comment by 3Dbastian** [comment]
@rcrswld opened an issues to GeoreferenceShape 
#34 -> further comments will be there regarding this topic

With respect to this:
* I will create a inital suggestions for that shacl till end of this week 
* I will include the bounding box there
-> then we can encapsulate it in all relevant Domain shacls (HD Map, Surface Model, Scenario, ...) as you suggested

**Comment by rcrswld** [comment]
Has been solved so far
