### ISSUE TITLE
All domain-specific shapes should embed GeneralShape

### ISSUE THREAD

**Issue by rcrswld** [GAIA-X4PLC-AAD/ontology-management-base#39]
reference to general-namespace should be included

**Comment by konierik** [comment]
Moin,

to do this I would like to suggest to add an object property to the general_ontology so we all use the same vocab for referencing (e.g. general:generalAttributeRef).
I commit a suggestion where the domain is void or maybe owl:Thing (as in everything can have general attributes) and the range is defined as General class.

Just a thought: Maybe it would also be nice if we could define a shape what classes must define a relation to the "General" Class (like all owl:Class, or just gx:Resource or something like that)

**Comment by konierik** [comment]
added the property.
@rcrswld, @jtdemer , @robertschubert , @lenasauermann, @MircoNierenz please have a look :)

**Comment by lenasauermann** [comment]
Where did you add the property  @konierik ? Where do we need to look?

**Comment by konierik** [comment]
Sorry, I changed the [general_ontology.ttl](https://github.com/GAIA-X4PLC-AAD/ontology-management-base/blob/Ontology_General/general/general_ontology.ttl) in the Ontology_general branch.

**Comment by robertschubert** [comment]
Hint: with PR https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/40 we added a description how to nest the general shape.

**Comment by robertschubert** [comment]
@rcrswld can we close this issue?

**Comment by rcrswld** [comment]
I checked the published SHACL for following data categories published in main-branch:
- environment-model
- hdmap
- scenario
- surface-model
All of them now includes 'GeneralShape'. Therefore, this issue can be closed.
