### ISSUE TITLE
Where is the code of the wizard?

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ontology-management-base#53]
https://sd-creation-wizard.gxfs.gx4fm.org/

Is it available open source?

**Comment by jtdemer** [comment]
Yes it can be found here: 
https://github.com/GAIA-X4PLC-AAD/self-description-creator

**Comment by robertschubert** [comment]
@jtdemer this is our signing tool for SDs.
The wizard is here:
https://gitlab.eclipse.org/eclipse/xfsc/self-description-tooling
and has two components:

- https://gitlab.eclipse.org/eclipse/xfsc/self-description-tooling/sd-creation-wizard-api (backend)
- https://gitlab.eclipse.org/eclipse/xfsc/self-description-tooling/sd-creation-wizard-frontend (web ui)

**Comment by lenasauermann** [comment]
@jdsika Can we close this issue?

**Comment by jdsika** [comment]
Maybe put the links in the wizard itself with a gitlab logo in the footer or in the readme here?

**Comment by robertschubert** [comment]
@jdsika feel free to close if PR70 is ok for you.
