### ISSUE TITLE
environment-model: _instance.json not conform to shacl shape

### ISSUE THREAD

**Issue by robertschubert** [GAIA-X4PLC-AAD/ontology-management-base#61]
We introduced a new CI pipeline which checks if the _instance.json conforms to the shacl shapes (see README.md).

There is no _instance.json file (but -instance.json). Please change this according the README.md.

The _instance.json file is not conform to the shacl.
To reproduce it locally please follow the `CI pipeline` section in the README.md.

Note that there is a new section "known issues" which describes a Bug of the wizard when not instanciating an optional field which has mandatory sub fields.

**Comment by MircoNierenz** [comment]
see https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/82

**Comment by robertschubert** [comment]
done. close issue.
