### ISSUE TITLE
GeoReference clarification and real world relations

### ISSUE THREAD

**Issue by heuerfin** [GAIA-X4PLC-AAD/ontology-management-base#81]
As discussed today we should harmonize and clarify some things regarding the georeferencing shape:

- Definition for BoundingBox. Should we fix the BoundingBox coordinates to a certain coordinates system? (e.g. EPSG:4326) This would make it easier to match e.g. the bounding box from a sensor trace to a map (without a transformation)
  - Should we introduce 2 BoundingBox'es: 1. for global harmonized system and 2. in the local map coordinate system
- Introduce a switch between "real world reference" and "no real world reference": to make it clear if it is synthetic or not

**Comment by MircoNierenz** [comment]
Do you need both bounding boxes at the same time or is an additional specification of the type of reference system enough - as mentioned as switch between ‘real world reference’ and ‘no real world reference’?

**Comment by MircoNierenz** [comment]
see https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/102
