### ISSUE TITLE
SD-Wizard does not process Logical Constraint Components

### ISSUE THREAD

**Issue by MircoNierenz** [GAIA-X4PLC-AAD/ontology-management-base#86]
If I use e.g. sh:xone in the shacl, all combinations are possible in the SD wizard, although only one field has to be entered explicitly.

I have attached a small shacle as well as 3 claims, where only one.json is valid. 
But it is recognised correctly at https://shacl.org/playground/.
[both.json](https://github.com/user-attachments/files/16529676/both.json)
[shacle_constraint_example.zip](https://github.com/user-attachments/files/16529691/shacle_constraint_example.zip)

**Comment by robertschubert** [comment]
@MircoNierenz 
please raise this issue in the sd-creation-wizard repository (you'll find the link in the readme)..
Please add a clear description what you expect from the frontend to visualize. This will help the developer to understand what is to be fixed.
after this this issue can be closed.

**Comment by MircoNierenz** [comment]
add issue to SD wizard repro and update readme issue chapter
