### ISSUE TITLE
Naming of property format type constistent through all shapes

### ISSUE THREAD

**Issue by lenasauermann** [GAIA-X4PLC-AAD/ontology-management-base#89]
The naming of the format type must be consistent through all shapes, so that we can filter for them in the portal / graph database.

hdmap --> type
surface model --> formatType
scenario --> dataFormat 
ositrace --> type
environment model --> dataType 

Please use ONE naming!!!

**Comment by MircoNierenz** [comment]
use formatType
see https://github.com/GAIA-X4PLC-AAD/ontology-management-base/pull/91

**Comment by robertschubert** [comment]
PR merged
