### ISSUE TITLE
BundleDataShape wrongly defined in GeneralShape

### ISSUE THREAD

**Issue by lenasauermann** [GAIA-X4PLC-AAD/ontology-management-base#94]
BundleDataShape has a minCount of 1 the GeneralShape, but the two properties of BundleDataShape  does not have a minCount. This makes no sense.

Possible Solutions:
1) Take out the minCount at BundleDataShape
2) Make at least one property of BundleDataShape required (minCount 1)
3) Add a new property the the BundleDataShape that is then required (minCount 1)

I would prefer Option 1

**Comment by lenasauermann** [comment]
FYI: If we take BundleDataShape out of General intoDataresourceExtension, we have the same issue there

**Comment by robertschubert** [comment]
PR is merged, ticket can be closed.
