### ISSUE TITLE
Instances are sometimes wrong

### ISSUE THREAD

**Issue by lenasauermann** [GAIA-X4PLC-AAD/ontology-management-base#95]
Some instances are wrong! Codeowners, please check your instances again! 

Our developers need correct test data ;)

**Comment by lenasauermann** [comment]
SD Creation might generate the JSONs wrong

**Comment by lenasauermann** [comment]
@robertschubert can we integrate a check "are there any additional claims beside what is defined in the shacl" to the json vs. shacl check?

**Comment by robertschubert** [comment]
@lenasauermann 
It would helf if you specifiy the ontologies where you spotted a concrete error :)

To your question, if we can adjust the validation:
Yes, we can do this with the help of `sh:closed true`.
Example:
```
ex:MyShape a sh:NodeShape ;
    sh:targetClass ex:MyClass ;
    sh:closed true ; # Activates the strict validation so additional fields in the jsonld are not allowed anymore.
```
Each domain (functional code owner) needs to decide if they want to have a `closed` definition or not.

**Comment by lenasauermann** [comment]
When we add sh:closed true, we would see every error, right? :D I can try to write down/mark every error but I propably oversee a few...

**Comment by lenasauermann** [comment]
**Scenario:**

Im type Scenario:scenario --> müsste Scenario:Scenario sein. Ist schon im shacl falsch!

general:DataResource --> just wrong, does not need to be there

general:media --> doubles at the end

georeference:georeference --> doubles too


**OsiTrace:**

startTime nicht korrekt

**HdMap:**

in "hdmap:general" ist "general:media", "general:requiredData" und "hdmap:speedLimit" fälschlicherweise drin

**Comment by lenasauermann** [comment]
@heuerfin @rcrswld  Can you take care about Scenario... there are the most errors (even in the shacl)

**Comment by robertschubert** [comment]
ein funktionierend hdmap-example anbei 
[hdmap-working.json](https://github.com/user-attachments/files/17376950/hdmap-working.json)
